# TOML configuration

source_dirs = ["/home/rafael/Pictures", "/home/rafael/Downloads/datalake"]
dest_dir_pictures = "/home/rafael/Pictures2/Pictures"
dest_dir_pictures_raw = "/home/rafael/Pictures2/Pictures_RAW"

# child directory in both destination directory pictures that 
no_exif_directories_both = 'no_exif'

